spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: daotai221192
    password: puaxvojtspjqaxsi
    properties:
      mail:
        smtp:
          auth: ntrue
          starttls:
            enable: true