version: '3.7'

services:
  app-server:
    build:
      context: polling-app-server
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      - db
    networks: 
      - backend
      - frontend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: callicoder
      SPRING_DATASOURCE_PASSWORD: callicoder

  app-client:
    build: 
      context: polling-app-client
      dockerfile: Dockerfile
      args: 
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    restart: always
    ports: 
      - "3000:80"
    depends_on:
      - app-server
    networks: 
      - frontend

  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    networks: 
      - backend
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-data:

networks:
  backend:
  frontend: